#!/bin/bash
if [ -x "$(command -v gcc)" ]; then
    if [ -x "$(command -v cmake)" ]; then
        cmake . 

        cmake --build . --target Shell --config Debug
    else 
        echo "Need to install CMake or make!" 
    fi

    if [ -f "./bin/Shell" -a ! -f "run_shell"  ]; then
        ln -s ./bin/Shell run_shell
    fi
else
    echo "Need to install GCC"
fi