#!/bin/bash
if [ -x "$(command -v gcc)" ]; then
    if [ -x "$(command -v cmake)" ]; then
        cmake . 
    else 
        echo "Need to install CMake!" 
    fi

    if [ -x "$(command -v make)" ]; then
        make 
    else
        echo "Need to install make!" 
    fi

    if [ -f "./bin/Shell" -a ! -f "run_shell"  ]; then
        ln -s ./bin/Shell run_shell
    fi
else
    echo "Need to install GCC"
fi